training:
  model:
    model_name: resnet50
    num_input_channels: 3
    num_classes: 1000
    pretrained: false
    weights: IMAGENET1K_V1
    is_external: false
    random_seed:
    path_configs:
      model_arch_path:
      model_weights_path:
    norm_config:
      add_norm_layer: false
      norm_mean:
      - 0.5
      - 0.5
      - 0.5
      norm_std:
      - 0.5
      - 0.5
      - 0.5
  dataset:
    dataset_name: IMAGENET
    num_classes: 1000
    train_dataset_path: /local/scratch/datasets/ImageNet/ILSVRC2012/train/
    test_dataset_path: /local/scratch/datasets/ImageNet/ILSVRC2012/val/
    preprocessing:
      steps:
      - name: Resize
        params:
          size: 256
      - name: CenterCrop
        params:
          size: 224
      - name: ToImage
        params:
      - name: ToDtype
        params:
          dtype: torch.float32
          scale: true
      - name: Normalize
        params:
          mean:
          - 0.485
          - 0.456
          - 0.406
          std:
          - 0.229
          - 0.224
          - 0.225

    download: true
  dataloader:
    train:
      num_workers: 4
      shuffle: true
      drop_last: false
      pin_memory: true
      batch_size: 64
    test:
      num_workers: 4
      shuffle: true
      drop_last: true
      pin_memory: true
      batch_size: 128
  device:
    use_ddp: true
    processor: cuda
    gpu_ids: [0,4,5]
  training:
    epochs: 10
    learning_rate: 0.001
    optimizer: adam
    optimizer_kwargs:
      weight_decay: 0.0001
    scheduler: LINEAR_LR
    scheduler_kwargs:
    criterion: cross_entropy
    save_final_model: false
    save_model_path:
    save_model_name:
    save_checkpoint: false
    save_checkpoint_path:
    save_checkpoint_name:
    checkpoint_interval: 1
    load_checkpoint: false
    load_checkpoint_path:
    verbose: true
adversarial_training:
  models:
  attacks:
    -  fgsm: ./fgsm_attack_base_config.yml
